services:
  db:
    image: postgis/postgis:17-3.5-alpine
    container_name: db
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jumbo
      POSTGRES_PASSWORD: jumbo
      POSTGRES_DB: jumbo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U jumbo" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - jumbo
  flyway:
    image: flyway/flyway:latest
    entrypoint: [ "flyway", "-url=jdbc:postgresql://db:5432/jumbo", "-user=jumbo", "-password=jumbo", "-locations=filesystem:/flyway/sql", "-baselineOnMigrate=true", "-connectRetries=60", "migrate" ]
    volumes:
      - ./migration:/flyway/sql
    depends_on:
      - db
    networks:
      - jumbo
  db_seed:
    restart: on-failure
    build:
      context: ./python
    depends_on:
      - db
      - flyway
    networks:
      - jumbo
networks:
  jumbo:
    driver: bridge
